
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
authors = [
    {name = "tabading", email = "tabading@student.42wolfsburg.de"}
]
license = {text = "MIT"}
requires-python = ">=3.7"
